### ISSUE TITLE
For Android Platform

### ISSUE THREAD

**Issue by wendux** [Lision/WKWebViewJavascriptBridge#1]
WebViewJavascriptBridge For Android: https://github.com/wendux/WebViewJavascriptBridge .

This Android version project is a mirror of [marcuswestin/WebViewJavascriptBridge(Object-c)](https://github.com/marcuswestin/WebViewJavascriptBridge) and [Lision/WKWebViewJavascriptBridge(Swift)](https://github.com/Lision/WKWebViewJavascriptBridge)  , so there are some similarities , such as API design, native code, and the example demo. For the Javascript code, it is exactly the same.

Welcome suggestions and criticism !

@Lision

**Comment by Lision** [comment]
Hi~ @wendux 
Good Job! 
Emmmmm... But this framework has made some changes. 
For example, do not rely on intercept requests for messaging.
So... For the Javascript code, there are also some minor changes.

**Comment by wendux** [comment]
If want to be compatible with [WebViewJavascriptBridge For Android](https://github.com/wendux/WebViewJavascriptBridge), the users should  modify the `setupWebViewJavascriptBridge` to :
```javascript
function setupWebViewJavascriptBridge(callback) {
    var bridge=window.WebViewJavascriptBridge||window.WKWebViewJavascriptBridge
	if (bridge) { return callback(bridge); }
	var callbacks=window.WVJBCallbacks||window.WKWVJBCallbacks
	if (callbacks) { return callbacks.push(callback); }
	window.WVJBCallbacks=window.WKWVJBCallbacks = [callback];
	if(window.WKWebViewJavascriptBridge){
	  window.webkit.messageHandlers.iOS_Native_InjectJavascript.postMessage(null)
	}
}
```
The code above can still run right on Android.
