### ISSUE TITLE
设置webView.customUserAgent导致JS交互无效

### ISSUE THREAD

**Issue by LiuSky** [Lision/WKWebViewJavascriptBridge#13]
设置webView.customUserAgent导致JS交互无效

**Comment by Lision** [comment]
纳尼？customUserAgent ？亲测没影响 可以从现有 Demo 中改一下试试？

**Comment by LiuSky** [comment]
3Q @Lision

**Comment by LOG-TAG** [comment]
@Lision we can use this MacOS cocoa development?
