### ISSUE TITLE
swift initializer is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by gianlucainnocente** [Lision/WKWebViewJavascriptBridge#16]
Hi, using swift 4.2 i got this error on the WKWebViewJavascriptBridge extension in WKWebViewJavascriptBridge.swift file:
`swift initializer is inaccessible due to 'private' protection level`

The error is caused by "webview" in line 83, "base" in line 90 and "flushMessageQueue()" in line 94.
The problem is that it can't access these properties/methods beacause they are private..

**Comment by Lision** [comment]
Hi, first of all, sry to reply late.
Emmmmm... I try to run the demo by using swift 4.2,
and there is no any error no even warning.
