### ISSUE TITLE
关于 WKWebViewJavascriptBridge 的实现方式有一点疑问

### ISSUE THREAD

**Issue by Jiar** [Lision/WKWebViewJavascriptBridge#17]
你好

我看了下源码，发现从`js`向`native`发送消息的部分的实现是采用了之前在`UIWebView`上使用`Bridge`的方式：是在`js`中保存`sendMessageQueue`变量，然后在`native`中调用`_fetchQueue()`的方式来实现的。

这里有一点疑问，`WKWebView`提供了`WKScriptMessageHandler`，可以通过代理拿到`WKScriptMessage`，而这个对象中包含了由`js`发送的消息，为什么不采用这种方式呢。

**Comment by Lision** [comment]
Emmmmm... 尴尬的是，我很久没看里面的代码了...

那么，如你所说，拿到 `WKScriptMessageHandler` 里面的的 `WKScriptMessage` 是一件挺简单的事情。可是这个 msg handler 是需要按照 name 注册的，如果根据业务注册一堆 msg handler 也不是不可以，不过考虑到维护起来的成本以及其他用户的使用，不如注册一个 handler 然后统一从某处找 msg 来处理...

我不知道我有没有表述清楚哈

**Comment by Jiar** [comment]
其实也不需要注册一堆`WKScriptMessageHandler`，毕竟这个`WKScriptMessageHandler`只是一个`native`和`js`之间的通道而已。

目前我公司里的做法就是只注册了一个`WKScriptMessageHandler`，然后在`message`中增加了`handlerName`、`data`、`callbackId`，使用`handlerName`来进行业务上的区分；`data`则是传递过来的数据；在`native`回调`js`的时候，通过`callbackId`在`js`内找到保存的`callback`执行达到回调目的。

我觉得这也是个不错的方式。

**Comment by Lision** [comment]
哦，我明白你的意思了哈。
确实可以节省一次交互~ 以后有时间的话我会优化一下这部分逻辑~
