### ISSUE TITLE
When setupWKWebViewJavascriptBridge  in React.js ,  will show  'WKWebViewJavascriptBridge' is not defined , how to fix that ?

### ISSUE THREAD

**Issue by ceu** [Lision/WKWebViewJavascriptBridge#19]
function setupWKWebViewJavascriptBridge(callback) {
    if (window.WKWebViewJavascriptBridge) { return callback(WKWebViewJavascriptBridge); }
    if (window.WKWVJBCallbacks) { return window.WKWVJBCallbacks.push(callback); }
    window.WKWVJBCallbacks = [callback];
    window.webkit.messageHandlers.iOS_Native_InjectJavascript.postMessage(null)
}

**Comment by Lision** [comment]
Did the WKWebView load the js?

**Comment by ceu** [comment]
yes ,    I  change  WKWebViewJavascriptBridge  to window.WKWebViewJavascriptBridge, in react it's  Ok.
