### ISSUE TITLE
iOS8.0不支持吗？

### ISSUE THREAD

**Issue by a714857512** [Lision/WKWebViewJavascriptBridge#2]
问题如题目。

**Comment by Lision** [comment]
@a714857512 你好

嘛~ 理论上 Cocoapods 支持 iOS 8
但是，由于 iOS WKWebView 的一些 API 没放出来
例如：customUserAgent
另：Carthage 也要求 iOS 9
So... 推荐 iOS 9 以上项目接入哟~

**Comment by a714857512** [comment]
感谢回复
Carthage我不太清楚是啥，好像也是一种管理工具，customUserAgent这个是有其他方法的，
如果只考虑与H5的交互问题的话，实际是可以支持iOS8的对吧。

**Comment by Lision** [comment]
@a714857512 
嗯

**Comment by a714857512** [comment]
我把你加的@available(iOS 9.0, *)限制去除的话是不是就可以支持了，我Swift的水平不是太好，不经常练

**Comment by Lision** [comment]
@a714857512 
(⊙v⊙)嗯 如果一定要兼容 iOS 8 的话

**Comment by a714857512** [comment]
好的，多谢
