### ISSUE TITLE
NoHandlerException, No handler for message from JS

### ISSUE THREAD

**Issue by pvn-anh-pham** [Lision/WKWebViewJavascriptBridge#26]
Sometime I get this error. Could you plz explain in which case we get this error?. 
Because this issue does not have any callback, so front-end just wait here forever, do we need a callback/event/delegate for this thing?

BR

**Comment by Lision** [comment]
This generally means that the method called by JS has no corresponding processing logic on the Swift side.

U can check if the `handlerName` is registered correctly on swift side, and U can also debug the JS code by referring to this article.

https://mattvanderpol.com/2013/08/14/how-to-debug-javascript-or-css-on-ios/
