### ISSUE TITLE
 注入的js是否可以和  WebViewJavascriptBridge_JS 一样？

### ISSUE THREAD

**Issue by ZD-Yin** [Lision/WKWebViewJavascriptBridge#27]
WKWebViewJavascriptBridgeJS  注入的 js 是否可以和   WebViewJavascriptBridgeJS 一样 , swift 代码这边去兼容就好，原来安卓 和 H5那边不用修改？

**Comment by Lision** [comment]
H5 似乎不可避免的需要做改动，因为这个库是依赖 WKWebView 的 messageHandlers 做的:

``` js
window.webkit.messageHandlers.iOS_Native_InjectJavascript.postMessage(null)
```

详细可以[点这里](https://lision.me/ios_native_js/)
