### ISSUE TITLE
当二次创建web时，报错

### ISSUE THREAD

**Issue by springlo** [Lision/WKWebViewJavascriptBridge#3]
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to add script message handler with name 'iOS_Native_InjectJavascript' when one already exists.'`

**Comment by springlo** [comment]
当退出web时，WKWebViewJavascriptBridge 没释放。

**Comment by Lision** [comment]
Hi~ @springlo 
很高兴你可以在发现问题时提 issue 给我哈！
看错误应该是重复 add 同名 msgHandler 所致，初步定为到了问题所在。
方便的话能否描述一下复现的场景和相关代码吗？
这可以帮助我校对。

**Comment by springlo** [comment]
就是我push一个vc，这个vc有wkwebview，然后我pop回去，重新进入界面，就报这个错。代码和你demo基本一样。

**Comment by Lision** [comment]
Hi~ @springlo 
很感谢你反馈的这个问题，已修复。
可以更新 v1.1.0 版本代码使用。

**Comment by Lision** [comment]
@springlo 
我将关闭这个 issue，如果 v1.1.0 仍发现问题，你可以重新打开此 issue 我们一起讨论哈~
