### ISSUE TITLE
WKWebViewJavascriptBridge: WARNING: no handler for message from iOS

### ISSUE THREAD

**Issue by ManishAhire** [Lision/WKWebViewJavascriptBridge#30]
Sometimes the handler is registered sometimes missing.

**Comment by arthurdapaz** [comment]
> Sometimes the handler is registered sometimes missing.

Where are you instantiating the "bridge" class?

Make sure that WKWebKit is fully loaded before initializing the bridge.

So, the best way to instantiate is inside viewDidLoad (for the controller that hosts your WKWebView)

Else you will get the alleged behavior.

Update: also don't forget to add the message handler

jsBridge.registerHandler(... handler name ...) { incomingData, callback in ... }

**Comment by ManishAhire** [comment]
> > Sometimes the handler is registered sometimes missing.
> 
> Where are you instantiating the "bridge" class?
> 
> Make sure that WKWebKit is fully loaded before initializing the bridge.
> 
> So, the best way to instantiate is inside viewDidLoad (for the controller that hosts your WKWebView)
> 
> Else you will get the alleged behavior

**Comment by ManishAhire** [comment]
@arthurdapaz Thanks for your response. 

Yes, I instantiated it in `viewDidLoad`.

`// setup bridge`
 `bridge = WKWebViewJavascriptBridge(webView: webView)`
