### ISSUE TITLE
Bridge error with no callback responseID

### ISSUE THREAD

**Issue by bugright** [Lision/WKWebViewJavascriptBridge#41]
<img width="1375" alt="截屏2022-03-12 上午12 07 19" src="https://user-images.githubusercontent.com/98653671/157904777-c3b3f5b9-2a86-4889-9156-85840b18740d.png">

**Comment by Lision** [comment]
不好意思，现在才处理 issue，我尝试从 Demo 调试发现可以正常工作，暂时关闭 issue。如果有问题可以回复，可以提供更多信息帮助我解决你的问题。
