### ISSUE TITLE
某些时候频繁快速重复传值给JS会失败，JS那边收不到数据导致界面空白

### ISSUE THREAD

**Issue by HZRZCW** [Lision/WKWebViewJavascriptBridge#44]
比如说打开一个页面，就调用 webView.bridge.call(handlerName: jsMethodName, data: json) { responseData in
            Log(responseData, tag: "js返回的数据")

        }，把json字符串传给JS，某些时候频繁快速重复传值给JS会失败，JS那边收不到数据导致界面空白。

**Comment by yzb-bei** [comment]
在decidePolicyForNavigationAction中处理_evaluateJavascript中加入队列。自测可以

**Comment by Lision** [comment]
暂时没有复现，可以提供一个可复现的 Demo 吗？

**Comment by Lision** [comment]
看描述似乎是 js 侧没来得及初始化 bridge 导致的？
- 可以观察如果丢数据只在某个点之前，这个点之后的函数调用则没有任何丢失，说明猜测正确。
- 如果同页面，丢失之前的某个点已经调用成功则说明我的猜测错误。
期待回复。 @HZRZCW

**Comment by HZRZCW** [comment]
> 看描述似乎是 js 侧没来得及初始化 bridge 导致的？
> 
> * 可以观察如果丢数据只在某个点之前，这个点之后的函数调用则没有任何丢失，说明猜测正确。
> * 如果同页面，丢失之前的某个点已经调用成功则说明我的猜测错误。
>   期待回复。 @HZRZCW

我调试了一下，发现是webview还没来得及初始化完毕就调用了这个方法导致没有真正执行：self.webView?.evaluateJavaScript(javascript, completionHandler: completion)

我在这个地方加个延时就没问题了：
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/12219811/178401407-a6309314-0e71-46c9-96c5-ec21cfe0af90.png">

**Comment by Lision** [comment]
@HZRZCW 好的，Demo 可以这么解决哈，工程建议使用 WKNavigationDelegate 的 func 判断是否完成 loading：
![image](https://user-images.githubusercontent.com/13974049/178435092-071da778-b247-4b4b-89e0-0bca83af2bba.png)
https://developer.apple.com/documentation/webkit/wknavigationdelegate

**Comment by HZRZCW** [comment]
> @HZRZCW 好的，Demo 可以这么解决哈，工程建议使用 WKNavigationDelegate 的 func 判断是否完成 loading： ![image](https://user-images.githubusercontent.com/13974049/178435092-071da778-b247-4b4b-89e0-0bca83af2bba.png) https://developer.apple.com/documentation/webkit/wknavigationdelegate

我试过在didFinish 方法 才 传值，少数时候还是会出现这种问题，但是像我上面说的那样改之后就再也没出现过。

**Comment by Lision** [comment]
@HZRZCW 在 start 做个记号，didFinish 消除记号，另外如果 load url 的 url 带有重定向之类的也需要考虑到，比较复杂。原则上就是 js 侧完成 setup bridge 后 native 再调用才可能传递成功哈。
bridge 本身是个比较轻量的简单库，这里我个人没有精力添加一个比较通用的 load 判定逻辑了，既然原因定位到了，这里先 close。
