### ISSUE TITLE
Add a git tag to simplify SPM integration process

### ISSUE THREAD

**Issue by muxinqi** [Lision/WKWebViewJavascriptBridge#46]
Since there is no tag for #37, the only way to integrate this package with SPM is to pin a specific commit hash. 

Adding a tag would make this better so that we can use a semantic version in the SPM integration.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/42941327/212866235-9c9c77f5-ab18-403c-b6e4-715f83350518.png">

I'd like to help with that, but I'm afraid that there is no way to make a pull request for just `add a tag` 😅, at least for now.

**Comment by Lision** [comment]
Thx, I have pushed a tag '1.2.3'. Hope this can help you.
