### ISSUE TITLE
I do not want to see print of wkwebkitJavascriptBridge.

### ISSUE THREAD

**Issue by Dabin22** [Lision/WKWebViewJavascriptBridge#7]
I am currently using wkwebkitjavascriptBridge so well. But this framework is too much print for debugging. Is there a way to control output statements as an option?

**Comment by Lision** [comment]
@Dabin22 
The log is not enabled by default in v1.2.0.
If u want see the log can do this:

``` objc
bridge = WKWebViewJavascriptBridge(webView: webView)
bridge.isLogEnable = true
```

**Comment by Dabin22** [comment]
@Lision 
Can I think of this feature since version 1.2?
