### ISSUE TITLE
请问在 Reactjs 中如何注册？

### ISSUE THREAD

**Issue by ceu** [Lision/WKWebViewJavascriptBridge#9]
how to setup  WKWebViewJavascriptBridge in ReactJS

@Lision

**Comment by potato04** [comment]
What are you going to do with this pod in Reactjs?

**Comment by ceu** [comment]
> What are you going to do with this pod in Reactjs?
I want to call swift function in Reactjs;     eg: call  Native Camera, photo album...

**Comment by potato04** [comment]
> > What are you going to do with this pod in Reactjs?
> > I want to call swift function in Reactjs;     eg: call  Native Camera, photo album...

Sorry, i thought you were asking about react-native -_-||
I think you could create a simple module to create/export function `setupWKWebViewJavascriptBridge` and import it in your react component?

**Comment by ceu** [comment]
> > > What are you going to do with this pod in Reactjs?
> > > I want to call swift function in Reactjs;     eg: call  Native Camera, photo album...
> 
> Sorry, i thought you were asking about react-native -_-||
> I think you could create a simple module to create/export function `setupWKWebViewJavascriptBridge` and import it in your react component?

HI,Thank you very much for helping me find the direction to solve this problem. I have solved this problem. Thank you again
